# Generated by Django 2.0.8 on 2018-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180920_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('conteudo', models.CharField(max_length=40000)),
            ],
        ),
    ]
