# Generated by Django 2.0.8 on 2018-09-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_noticias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
