# Generated by Django 2.0.8 on 2018-09-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180922_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('localizadao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sobre',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
