# Generated by Django 2.0.8 on 2018-10-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180926_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadeiraFundadoresTitulares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fundador_titular', models.CharField(max_length=150)),
                ('nome_membro_atual', models.CharField(max_length=150)),
                ('descricao_fundador_titular', models.CharField(max_length=250)),
                ('descricao_membro_atual', models.CharField(max_length=250)),
                ('imagem_membro_atual', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('in_memorian', models.BooleanField(default=False)),
            ],
        ),
    ]
